name: Comprehensive Build and Test

on:
  push:
    branches: [ master, upgrade/jdk-21-compatibility ]
  pull_request:
    branches: [ master ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'VDVIL'
        format: 'HTML'

  test:
    needs: dependency-check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [19, 21, 22]
      fail-fast: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: maven
        
    - name: Run tests with retries
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: mvn clean verify -P ex-integration jacoco:report
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-jdk${{ matrix.java-version }}
        path: |
          '**/target/surefire-reports/*.xml'
          '**/target/site/jacoco/index.html'

    - name: Performance Regression Check
      run: |
        mvn verify -P performance-test
        ./scripts/check-performance-regression.sh

  semantic-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check Semantic Versioning
      run: |
        mvn validate -P version-check
