name: Build and test
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'corretto'
          cache: 'maven'
      - name: Building the app
        run: mvn --batch-mode --file pom.xml --update-snapshots package -P ex-integration
