name: Publish to github repo

on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release repository Stiglau/VideoRenderer
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: publishing
        run: mvn --batch-mode source:jar deploy -P ex-integration
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}