# This workflow will build a Java project with Maven

# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Deploying based on Pull Request
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'corretto'
      - name: Building the app
        run: mvn --batch-mode --file pom.xml --update-snapshots package -P ex-integration
      #      - run: mkdir staging && cp target/*.jar staging
      #      - uses: actions/upload-artifact@v2
      #        with:
      #          name: Package
      #          path: staging
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up corretto JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'corretto'
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: v${{github.run_number}}
          release_name: Release V${{github.run_number}}

      - name: Update version
        run: mvn -B versions:set -DnewVersion=v${{github.run_number}} -DgenerateBackupPoms=false

      - name: Publish to GitHub Packages Apache Maven
        run: mvn -B deploy -DskipTests --file pom.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}